version: "3.3"
services:
  openhouse-tables:
    build:
      context: ../../../..
      dockerfile: tables-service.Dockerfile
    ports:
      - 8000:8080
    environment:
      - LOCAL_STORAGE_ACCOUNT_NAME=containerstorageabs
      - LOCAL_STORAGE_ACCOUNT_KEY= # add account key
      - AZURE_CLIENT_ID=005f5b8a-f69f-4e59-96fc-09334a45d64c # these are all for Kai's personal account, should switch when merged with main branch
      - AZURE_TENANT_ID=8050f649-c5b5-45a7-8f30-3e7dcd9c7b3d
      - AZURE_CLIENT_SECRET= # add secret
  openhouse-housetables:
    build:
      context: ../../../..
      dockerfile: housetables-service.Dockerfile
    ports:
      - 8001:8080
  openhouse-jobs:
    build:
      context: ../../../..
      dockerfile: jobs-service.Dockerfile
    ports:
      - 8002:8080
  openhouse-jobs-scheduler:
    build:
      context: ../../../..
      dockerfile: jobs-scheduler.Dockerfile
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml