cluster:
  name: "LocalFSCluster"
  storage:
    type: "hadoop"
    uri: "hdfs://namenode:9000/"
    root-path: "/data/openhouse"
  storages:
    default-type: "adls"
    types:
      adls:
        rootpath: "" 
        endpoint: "abfs://blobcontainer@containerstorageabs.dfs.core.windows.net/" # populate your values here
        parameters:
           adls.auth.shared-key.account.name: containerstorageabs # add your Azure Storage Account name here
<<<<<<< HEAD
           adls.auth.shared-key.account.key: # add your Azure Storage Account key here
=======
           adls.auth.shared-key.account.key:  # add your Azure Storage Account key here
>>>>>>> f02b0f5 (changes to fix client side)
  iceberg:
    write:
      format:
        default: "orc"
      metadata:
        previous-versions-max: 28
        delete-after-commit:
          enabled: true
  housetables:
    base-uri: "http://openhouse-housetables:8080"
    database:
      type: "MYSQL"
      url: "jdbc:mysql://mysql:3306/oh_db?allowPublicKeyRetrieval=true&useSSL=false"
  security:
    token:
      interceptor:
        classname: "com.linkedin.openhouse.common.security.DummyTokenInterceptor"
    tables:
      authorization:
        enabled: true
        opa:
          base-uri: "http://opa:8181"