cluster:
  name: "LocalFSCluster"
  storage:
    type: "hadoop"
    uri: "hdfs://namenode:9000/"
    root-path: "/data/openhouse"
  storages:
    default-type: "adls"
    types:
      adls:
        rootpath: "<BLOB_CONTAINER_NAME>@<STORAGE_ACCOUNT_NAME>.dfs.core.windows.net" # populate your values here
        endpoint: "abfs://"
        parameters:
           adls.auth.shared-key.account.name: STORAGE_ACCOUNT_NAME # add your Azure Storage Account name here
           adls.auth.shared-key.account.key: STORAGE_ACCOUNT_KEY # add your Azure Storage Account key here
  iceberg:
    write:
      format:
        default: "orc"
      metadata:
        previous-versions-max: 28
        delete-after-commit:
          enabled: true
  housetables:
    base-uri: "http://openhouse-housetables:8080"
    database:
      type: "MYSQL"
      url: "jdbc:mysql://mysql:3306/oh_db?allowPublicKeyRetrieval=true&useSSL=false"
  security:
    token:
      interceptor:
        classname: "com.linkedin.openhouse.common.security.DummyTokenInterceptor"
    tables:
      authorization:
        enabled: true
        opa:
          base-uri: "http://opa:8181"