apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-conf
data:
  cluster.yaml: |-
{{- if .Values.clusterPropertiesPath }}
{{- $path := .Values.clusterPropertiesPath }}
{{- $content := .Files.Get $path }}
{{- if $content }}
{{ if .Values.housetables.database.url }}
{{ $content |
  regexReplaceAllLiteral "<database-url>" .Values.housetables.database.url |
  nindent 4
}}
{{- else }}
{{ $content | nindent 4 }}
{{- end }}
{{- else }}
{{ fail (printf "File at %s not found or empty" $path) }}
{{- end }}
{{- else }}
{{ fail "clusterPropertiesPath is not defined" }}
{{- end }}
