cluster:
  name: "AKSCluster"
  storage:
    type: "hadoop"
    uri: "file:///"
    root-path: "/tmp/openhouse"
  iceberg:
    write:
      format:
        default: "orc"
      metadata:
        previous-versions-max: 78
        delete-after-commit:
          enabled: true
  housetables:
    base-uri: "http://openhouse-housetables-service:8080"
    database:
      type: "MYSQL"
      url: <database-url>
  security:
    token:
      interceptor:
        classname: "com.linkedin.openhouse.common.security.DummyTokenInterceptor"
    tables:
      authorization:
        enabled: false